In [1]:
import pandas as pd
import numpy as np
from torch import nn,optim
import torch.nn.functional as F
import torch
from torch.autograd import Variable

In [2]:
data=pd.read_csv(r'D:\personal\family\Machine Learning Projects Final\Datasets\Social_Network_Ads.csv')
data.head()

User ID  Age  EstimatedSalary
0  15624510   19            19000
1  15810944   35            20000
2  15668575   26            43000
3  15603246   27            57000
4  15804002   19            76000

In [3]:
data.columns

Index(['User ID', 'Age', 'EstimatedSalary'], dtype='object')

In [4]:
data.shape

(400, 3)

In [5]:
data.isnull().sum()

User ID            0
Age                0
EstimatedSalary    0
dtype: int64

In [6]:
X_temp=data.iloc[ : , 1:2 ].values
y_temp=data.iloc[ : , 2 : ].values

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_temp=scaler.fit_transform(X_temp)
y_temp=scaler.fit_transform(y_temp)

In [8]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X_temp,y_temp,test_size=0.1)

In [9]:
x_train1=Variable(torch.FloatTensor(x_train))
y_train1=Variable(torch.FloatTensor(y_train))

x_test1=Variable(torch.FloatTensor(x_test))
y_test1=Variable(torch.FloatTensor(y_test))

In [11]:
x_train1

tensor([[-1.8773],
        [ 0.2240],
        [ 0.7971],
        [ 0.4150],
        [ 1.8477],
        [ 0.9881],
        [ 0.3195],
        [-1.0177],
        [-1.2087],
        [ 1.4656],
        [ 1.5612],
        [ 0.7971],
        [-1.4953],
        [ 0.3195],
        [ 1.3701],
        [-0.6356],
        [-1.6863],
        [-0.0626],
        [ 0.7015],
        [ 0.7015],
        [ 0.8926],
        [-1.8773],
        [-1.6863],
        [ 2.0387],
        [-1.0177],
        [ 1.0836],
        [ 1.3701],
        [-0.7312],
        [ 0.1285],
        [-1.1132],
        [-1.1132],
        [-0.2536],
        [-0.1581],
        [ 0.8926],
        [ 0.7015],
        [ 0.9881],
        [ 0.8926],
        [ 0.8926],
        [-0.8267],
        [-0.1581],
        [-0.0626],
        [ 0.3195],
        [ 0.7015],
        [ 0.9881],
        [-0.2536],
        [ 0.4150],
        [ 0.7971],
        [ 2.0387],
        [-0.5401],
        [-0.5401],
        [ 0.9881],
        [ 1.0836],
        [-0.

In [10]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        
        
        self.f1=torch.nn.Linear(1,1)
        
    def forward(self,x):
        x=self.f1(x)        
        return x

In [11]:
m1=Net()
loss_func=nn.MSELoss()
optm=optim.SGD(m1.parameters(),lr=0.0001)

In [12]:
for epoch in range(500):
    y_pred=m1(x_train1)
    loss=loss_func(y_pred,y_train1)
    loss.backward()
    optm.step()

In [13]:
result=m1(x_test1)

In [14]:
result=result.detach().numpy()

In [15]:
result=np.expm1(result)

In [16]:
result=scaler.inverse_transform(result)

In [17]:
result

array([[153669.03 ],
       [ 81527.   ],
       [141904.62 ],
       [ 65801.195],
       [ 76956.195],
       [ 95293.2  ],
       [ 89349.72 ],
       [ 89349.72 ],
       [ 65801.195],
       [ 83998.875],
       [ 86604.055],
       [121778.08 ],
       [ 60095.195],
       [ 95293.2  ],
       [ 98507.44 ],
       [ 86604.055],
       [ 67425.055],
       [ 65801.195],
       [ 83998.875],
       [ 61411.355],
       [ 56537.17 ],
       [105465.234],
       [131313.3  ],
       [ 74844.664],
       [105465.234],
       [131313.3  ],
       [ 83998.875],
       [ 83998.875],
       [ 56537.17 ],
       [105465.234],
       [105465.234],
       [136469.94 ],
       [ 86604.055],
       [ 92243.44 ],
       [ 76956.195],
       [ 60095.195],
       [ 98507.44 ],
       [ 64260.426],
       [197373.62 ],
       [ 83998.875]], dtype=float32)

# Another Example

In [19]:
m2=Net()
loss_func=nn.MSELoss(size_average=False)
optm=optim.SGD(m2.parameters(),lr=0.01)

In [20]:
x_data=torch.Tensor([[1],[2],[3]])
y_data=torch.Tensor([[3],[6],[9]])

In [21]:
type(x_data)

torch.Tensor

In [22]:
x_data.shape

torch.Size([3, 1])

In [23]:
x_data

tensor([[1.],
        [2.],
        [3.]])

In [24]:
for epoch in range(500):
    y_pred=m2(x_data)
    loss=loss_func(y_pred,y_data)
    optm.zero_grad()
    loss.backward()
    optm.step()
    

In [70]:
z=Variable(torch.Tensor([[4.0],[5.0]]))


In [85]:
predict_value=m2(z)

In [86]:
predict_value

tensor([[11.9607],
        [14.9379]], grad_fn=<AddmmBackward>)